
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import static java.lang.Class.forName;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class mainwin extends javax.swing.JFrame {

  Admin dbConnection = new Admin();
   
    public mainwin() {
        initComponents();
        showdate();
        showtime();
        jLabel4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passtxt = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        nametxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        timelabel = new javax.swing.JLabel();
        datelabel = new javax.swing.JLabel();
        timelabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        positioncombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passtxtKeyPressed(evt);
            }
        });
        getContentPane().add(passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 140, 30));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, -1, -1));

        nametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nametxtKeyPressed(evt);
            }
        });
        getContentPane().add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 140, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter Account Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 360, -1, 30));

        timelabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        timelabel.setForeground(new java.awt.Color(255, 255, 255));
        timelabel.setText("I MIND MA BUSINESS SUPER MARKET");
        getContentPane().add(timelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 710, 40));

        datelabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        datelabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(datelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 290, 40));

        timelabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        timelabel1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(timelabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 290, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 210, 20));

        positioncombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Administrator", "Sales Person" }));
        getContentPane().add(positioncombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 140, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Enter Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, 30));

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Validation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 300, 240));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue-light-animation-effect-for-backgroundloop-able_mjdrkiyd__F0000.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 600));

        jMenu1.setText("About");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        login();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nametxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nametxtKeyPressed
        
    }//GEN-LAST:event_nametxtKeyPressed

    private void passtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passtxtKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            login();
        }
    }//GEN-LAST:event_passtxtKeyPressed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
       AboutMe about = new AboutMe();
       about.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainwin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainwin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainwin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainwin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainwin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datelabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField nametxt;
    private javax.swing.JPasswordField passtxt;
    private javax.swing.JComboBox<String> positioncombo;
    private javax.swing.JLabel timelabel;
    private javax.swing.JLabel timelabel1;
    // End of variables declaration//GEN-END:variables

    public void showdate(){
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        datelabel.setText(s.format(d));
    }
    
    public void showtime(){
        new Timer(0,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                timelabel1.setText(s.format(d));
            }
        }).start();
    }
    
    
    
    
    public void login(){
        
      
                 try{
                    dbConnection.dbConnect();
                    dbConnection.pst = dbConnection.con.prepareStatement("SELECT * FROM salespersons WHERE position = ? AND salespersonsid=? AND password=?");
                    
                    dbConnection.pst.setString(1, positioncombo.getSelectedItem().toString());
                    dbConnection.pst.setString(2,nametxt.getText());
                    dbConnection.pst.setString(3,passtxt.getText());
                    
                    dbConnection.rs = dbConnection.pst.executeQuery();
                    
                    if(dbConnection.rs.next()){
                       if(positioncombo.getSelectedItem().equals("Administrator")){
                         insertEvent();
                        Admin adminwin = new Admin();
                        adminwin.setVisible(true);
                        adminwin.loginlabel(nametxt.getText());
                        this.dispose();
                       }else{
                           insertEvent();
                           saleswin sales = new saleswin();
                           sales.setVisible(true);
                           sales.username(nametxt.getText());
                           this.dispose();
                       }
                        
                    }else{
                        jLabel4.setText("INCORRECT USERNAME OR PASSWORD");
                        jLabel4.setForeground(Color.RED);
                        jLabel4.setVisible(true);
                    }
                    
                    dbConnection.dbClose();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(this,e);
                }
            
      
    }
    
    public void insertEvent(){
        
        try{
            dbConnection.dbConnect();
            dbConnection.pst = dbConnection.con.prepareStatement("INSERT INTO `events`( `SalesPersonsId`, `Action`, `Date`, `Time`) "
                    + "VALUES (?,?,?,?)");
            dbConnection.pst.setString(1,nametxt.getText());
            dbConnection.pst.setString(2,"LoggedIn");
            dbConnection.pst.setString(3,datelabel.getText());
            dbConnection.pst.setString(4,timelabel1.getText());
            
            dbConnection.pst.executeUpdate();
            
            dbConnection.dbClose();
        }catch(Exception e){
             JOptionPane.showMessageDialog(this,e);
        }
    }
}
